"""P3-22: isolated upload feedback using fictional names and generated bytes."""
import asyncio
import builtins
import io
import json
import zipfile

import pytest
from fastapi import HTTPException, UploadFile
from PIL import Image

from app.routes import mapping
from app.services import background_removal, spreadsheet, storage
from app.services.admin_settings import FaceDetectionSettings
from app.services.image_messages import BACKGROUND_FAILURE, HEIC_MESSAGE


class Request:
    async def is_disconnected(self):
        return False


@pytest.fixture(autouse=True)
def isolated(tmp_path, monkeypatch):
    monkeypatch.setattr(storage, "BASE_DATA", tmp_path / "data")
    monkeypatch.setattr(mapping, "enforce_workspace_write", lambda *args: None)
    monkeypatch.setattr(mapping, "get_face_detection_settings", lambda: FaceDetectionSettings(
        enable_background_removal_ops=True, enable_center_on_face_ops=True,
    ))


def zip_bytes(files):
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w") as archive:
        for name, content in files.items():
            archive.writestr(name, content)
    return out.getvalue()


def png():
    out = io.BytesIO()
    Image.new("RGB", (40, 40), "red").save(out, "PNG")
    return out.getvalue()


@pytest.mark.parametrize("ext", ["heic", "HEIF"])
@pytest.mark.parametrize("advanced", [False, True])
def test_portrait_zip_heic_feedback(ext, advanced):
    result = spreadsheet.ingest_spreadsheet(
        "fictional", io.BytesIO(b"First Name,Last Name\nAnn,Lee\n"), "roster.csv",
        io.BytesIO(zip_bytes({f"Ann_Lee.{ext}": b"synthetic"})),
        advanced_name_match=advanced,
    )
    assert any(HEIC_MESSAGE in warning for warning in result.warnings)


def test_baby_zip_pdf_option_and_heic_feedback():
    result = asyncio.run(mapping.upload_baby_zip(
        Request(), workspace_id="fictional",
        people_json=json.dumps([{"index": 1, "first_name": "Ann", "last_name": "Lee"}]),
        baby_zip=UploadFile(filename="baby.zip", file=io.BytesIO(zip_bytes({
            "Ann_Lee.pdf": b"synthetic", "Ann_Lee.heic": b"synthetic",
        }))), advanced_name_match=True, partial_name_match=False, convert_pdfs=False,
        remove_background=False, background_mode="simple",
    ))
    assert any('"Convert PDFs in baby ZIP"' in warning for warning in result.warnings)
    assert any(HEIC_MESSAGE in warning for warning in result.warnings)


@pytest.mark.parametrize("kind", ["baby", "mugshot"])
@pytest.mark.parametrize("ext", ["heic", "HEIF"])
def test_single_image_heic_feedback(kind, ext):
    with pytest.raises(HTTPException) as caught:
        asyncio.run(mapping.upload_image(
            Request(), workspace_id="fictional", kind=kind,
            file=UploadFile(filename=f"photo.{ext}", file=io.BytesIO(b"synthetic")),
            remove_background=False, background_mode="simple",
        ))
    assert caught.value.status_code == 400
    assert caught.value.detail == HEIC_MESSAGE


def fail(*args, **kwargs):
    raise RuntimeError("OpenCV rembg Python internal failure")


def test_background_failure_does_not_expose_internals(monkeypatch):
    monkeypatch.setattr(mapping, "try_reserve_bg_job", lambda *args: (True, ""))
    monkeypatch.setattr(mapping, "release_bg_job", lambda *args: None)
    monkeypatch.setattr(mapping, "remove_background_bytes", fail)
    with pytest.raises(HTTPException) as caught:
        asyncio.run(mapping.upload_image(
            Request(), workspace_id="fictional", kind="baby",
            file=UploadFile(filename="photo.png", file=io.BytesIO(png())),
            remove_background=True, background_mode="simple",
        ))
    assert caught.value.detail == BACKGROUND_FAILURE


def test_face_failure_does_not_expose_internals(monkeypatch):
    from app.services import face_detection
    monkeypatch.setattr(face_detection, "detect_face_box_for_editor_with_meta", fail)
    with pytest.raises(HTTPException) as caught:
        asyncio.run(mapping.detect_face_center_api(UploadFile(filename="photo.png", file=io.BytesIO(png()))))
    assert caught.value.status_code == 503
    assert "manually" in caught.value.detail
    assert "OpenCV" not in caught.value.detail


@pytest.mark.parametrize("operation", [background_removal._acquire_rembg_session, background_removal._remove_background_ultra_complex])
def test_missing_background_library_has_plain_feedback(monkeypatch, operation):
    original = builtins.__import__
    def blocked(name, *args, **kwargs):
        if name == "rembg":
            raise ImportError("synthetic missing package")
        return original(name, *args, **kwargs)
    monkeypatch.setattr(builtins, "__import__", blocked)
    with pytest.raises(ValueError) as caught:
        operation() if operation is background_removal._acquire_rembg_session else operation(png())
    assert "Try Simple or Complex" in str(caught.value)
    assert "rembg" not in str(caught.value)


def test_baby_zip_background_failure_has_plain_warning(monkeypatch):
    monkeypatch.setattr(mapping, "remove_background_bytes", fail)
    result = asyncio.run(mapping.upload_baby_zip(
        Request(), workspace_id="fictional",
        people_json=json.dumps([{"index": 1, "first_name": "Ann", "last_name": "Lee"}]),
        baby_zip=UploadFile(filename="baby.zip", file=io.BytesIO(zip_bytes({"Ann_Lee.png": png()}))),
        advanced_name_match=True, partial_name_match=False, convert_pdfs=False,
        remove_background=True, background_mode="simple",
    ))
    assert any("original photo was kept" in warning for warning in result.warnings)
    assert result.people[0].baby_photo_filename
    assert all("OpenCV" not in warning for warning in result.warnings)


@pytest.mark.parametrize("preview", [False, True])
def test_background_job_failure_has_plain_status(monkeypatch, preview):
    storage.save_upload("fictional", "baby/photo.png", io.BytesIO(png()))
    monkeypatch.setattr(mapping, "try_reserve_bg_job", lambda *args: (True, ""))
    monkeypatch.setattr(mapping, "release_bg_job", lambda *args: None)
    monkeypatch.setattr(mapping, "start_bg_job", lambda *args, **kwargs: None)
    monkeypatch.setattr(mapping, "remove_background_bytes", fail)
    updates = []
    monkeypatch.setattr(mapping, "update_bg_job", lambda job, **kwargs: updates.append(kwargs))
    class ImmediateThread:
        def __init__(self, target, **kwargs):
            self.target = target
        def start(self):
            self.target()
    monkeypatch.setattr(mapping, "Thread", ImmediateThread)
    operation = mapping.remove_background_preview_job if preview else mapping.remove_background_job
    kwargs = {"force": False} if preview else {}
    asyncio.run(operation(
        Request(), workspace_id="fictional", kind="baby", filename="photo.png",
        background_mode="simple", **kwargs,
    ))
    assert updates[-1]["error"] == BACKGROUND_FAILURE
