import { test, expect } from '@playwright/test';
import path from 'node:path';
import { activate } from './helpers';

test('layout edits, gesture history, renumber and reload on fictional template', async ({page}) => {
  await activate(page);
  const project = path.resolve('.e2e-data/project');
  await page.locator('input[type=file]').nth(0).setInputFiles(path.join(project,'annotated.png'));
  await page.locator('input[type=file]').nth(1).setInputFiles(path.join(project,'clean.png'));
  await page.getByRole('button',{name:'Parse template',exact:true}).click();
  const canvas = page.getByRole('region',{name:'Template layout canvas'});
  await expect(canvas).toBeVisible();
  const portraits = canvas.locator('rect[data-label^="mugshot-"]');
  const originalCount = await portraits.count();
  await page.getByRole('button',{name:'Add slot',exact:true}).click();
  await expect(portraits).toHaveCount(originalCount+1);
  await page.getByRole('button',{name:'Duplicate slot',exact:true}).click();
  await expect(portraits).toHaveCount(originalCount+2);
  await page.getByRole('button',{name:'Delete slot',exact:true}).click();
  await page.getByRole('dialog',{name:'Delete selected slot?'}).getByRole('button',{name:'Delete slot',exact:true}).click();
  await expect(portraits).toHaveCount(originalCount+1);
  await page.getByRole('button',{name:'Undo layout',exact:true}).click();
  await expect(portraits).toHaveCount(originalCount+2);
  await page.getByRole('button',{name:'Redo layout',exact:true}).click();
  await expect(portraits).toHaveCount(originalCount+1);
  await portraits.first().click({position:{x:30,y:30}});
  await expect(canvas.locator('circle')).toHaveCount(4);
  const x = Number(await portraits.first().getAttribute('x'));
  await canvas.focus(); await page.keyboard.press('ArrowRight');
  await expect(portraits.first()).toHaveAttribute('x',String(x+1));
  await page.keyboard.press('Shift+ArrowRight');
  await expect(portraits.first()).toHaveAttribute('x',String(x+11));
  await page.keyboard.press('Control+z');
  await expect(portraits.first()).toHaveAttribute('x',String(x+1));
  await page.keyboard.press('Control+Shift+z');
  await expect(portraits.first()).toHaveAttribute('x',String(x+11));
  await portraits.first().click({position:{x:30,y:30}});
  const r = Number(await canvas.locator('circle').first().getAttribute('r'));
  await page.getByRole('button',{name:'Zoom in',exact:true}).click();
  await expect(page.getByText('125%',{exact:true})).toBeVisible();
  expect(Number(await canvas.locator('circle').first().getAttribute('r'))).toBeCloseTo(r/1.25);
  await page.getByRole('button',{name:'Fit template',exact:true}).click();
  await page.getByRole('button',{name:'Renumber slots',exact:true}).click();
  await portraits.nth(1).click({position:{x:30,y:30}});
  await portraits.nth(0).click({position:{x:30,y:30}});
  await page.getByRole('button',{name:'Apply order',exact:true}).click();
  await expect(canvas.locator('circle')).toHaveCount(0);
  await page.screenshot({path:'/tmp/f3-layout.png',fullPage:true});
  await page.waitForTimeout(1000);
  await page.reload();
  await expect(page.getByRole('button',{name:'Undo layout',exact:true})).toBeDisabled();
  await expect(portraits).toHaveCount(originalCount+1);
});
